version: '3.7'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
#      args:
#        PORT: 8081
    container_name: user-service
    ports:
      - "8081:8081"
    networks:
      - go-net
    env_file: ./user-service/.env

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    #      args:
#        PORT: 8082
    container_name: product-service
    ports:
      - "8082:8082"
    networks:
      - go-net
    env_file: ./product-service/.env

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
#      args:
#        PORT: ${PORT}
    container_name: order-service
    ports:
      - "8083:8083"
    networks:
      - go-net
    env_file: ./order-service/.env
    depends_on:
      - postgres

  postgres:
    image: "postgres:13.1"
    hostname: postgres
    container_name: postgres
    env_file: ./order-service/.env
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders
      - POSTGRES_USER=postgres
    ports:
      - "5433:5432"
    networks:
      - go-net

networks:
  go-net:
    name: go-network
    driver: bridge