version: '3.7'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    networks:
      - go-net
    env_file:
      - ./user-service/.env

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8082:8082"
    networks:
      - go-net
    env_file: ./product-service/.env

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8083:8083"
    networks:
      - go-net
    env_file: ./order-service/.env
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: "postgres:13.1"
    hostname: postgres
    container_name: postgres
    env_file: ./order-service/.env
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders
      - POSTGRES_USER=postgres
    ports:
      - "5433:5432"
    networks:
      - go-net

  rabbitmq:
    image: rabbitmq:3.7.15-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=order
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - go-net

networks:
  go-net:
    name: go-network
    driver: bridge